services:
  - type: web
    name: portafolio-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: RESEND_API_KEY
        sync: false
    healthCheckPath: /

