services:
  - type: web
    name: portafolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RESEND_API_KEY
        sync: false
    healthCheckPath: /

